name: flutterpractice
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  intl: ^0.17.0
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  # Place the flutter_icons configuration under the "flutter" section
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
